name            = "senta-pua-worker"
main            = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding  = "DB"
database_name = "senta-pua-db"
database_id   = "COLE_O_ID_AQUI_APOS_wrangler_d1_create"

[vars]
AMBIENTE = "production"
